import {getChatGPTUser} from "../../chatgpt-auth";
import {getBinding} from "@/db";
import {postExists} from "@/lib/content-store";
import {isOwner} from "@/lib/owner";
const bad=(text:string,status=400)=>Response.json({error:text},{status});
export async function GET(req:Request){const u=await getChatGPTUser();if(!u)return bad("로그인이 필요합니다.",401);const key=new URL(req.url).searchParams.get("post")??"";if(!await postExists(key))return bad("게시물을 찾을 수 없습니다.",404);try{const {results}=await getBinding().prepare("SELECT * FROM comments WHERE post_key=? ORDER BY created_at,id").bind(key).all<{id:string;user_id:string;author_name:string;body:string;created_at:string;updated_at:string}>();return Response.json({comments:results.map(c=>({id:c.id,authorName:c.author_name,body:c.body,createdAt:c.created_at,updatedAt:c.updated_at,canEdit:c.user_id===u.userId,canDelete:c.user_id===u.userId||isOwner(u)}))},{headers:{"Cache-Control":"private, no-store"}});}catch(e){console.error(e);return bad("댓글을 불러오지 못했습니다.",500);}}
export async function POST(req:Request){const u=await getChatGPTUser();if(!u)return bad("로그인이 필요합니다.",401);try{const input=await req.json();if(!input||typeof input!=="object")return bad("입력값을 확인해 주세요.");const p=input as Record<string,unknown>;if(typeof p.post!=="string"||!await postExists(p.post)||typeof p.body!=="string"||!p.body.trim()||p.body.length>2000)return bad("댓글은 1~2,000자로 입력해 주세요.");const now=new Date().toISOString();await getBinding().prepare("INSERT INTO comments(id,post_key,user_id,author_name,body,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),p.post,u.userId,(u.fullName??"사용자").slice(0,80),p.body.trim(),now,now).run();return Response.json({saved:true},{status:201});}catch(e){console.error(e);return bad("댓글을 저장하지 못했습니다.",500);}}
export async function PATCH(req:Request){const u=await getChatGPTUser();if(!u)return bad("로그인이 필요합니다.",401);try{const input=await req.json();if(!input||typeof input!=="object")return bad("입력값을 확인해 주세요.");const p=input as Record<string,unknown>;if(typeof p.id!=="string"||typeof p.body!=="string"||!p.body.trim()||p.body.length>2000)return bad("댓글을 확인해 주세요.");const r=await getBinding().prepare("UPDATE comments SET body=?,updated_at=? WHERE id=? AND user_id=?").bind(p.body.trim(),new Date().toISOString(),p.id,u.userId).run();return r.meta.changes?Response.json({saved:true}):bad("수정할 수 없는 댓글입니다.",403);}catch(e){console.error(e);return bad("댓글을 수정하지 못했습니다.",500);}}
export async function DELETE(req:Request){const u=await getChatGPTUser();if(!u)return bad("로그인이 필요합니다.",401);try{const input=await req.json();if(!input||typeof input!=="object")return bad("입력값을 확인해 주세요.");const p=input as Record<string,unknown>;if(typeof p.id!=="string")return bad("댓글을 확인해 주세요.");const r=await getBinding().prepare("DELETE FROM comments WHERE id=? AND (user_id=? OR ?=1)").bind(p.id,u.userId,isOwner(u)?1:0).run();return r.meta.changes?Response.json({deleted:true}):bad("삭제할 수 없는 댓글입니다.",403);}catch(e){console.error(e);return bad("댓글을 삭제하지 못했습니다.",500);}}
