"use client";
import {ChangeEvent,useState} from "react";
import {Download,RefreshCw,Upload} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {toast} from "sonner";

export function DataBackup(){
  const [busy,setBusy]=useState<"export"|"restore"|null>(null),[result,setResult]=useState("");
  async function download(){setBusy("export");setResult("");try{const response=await fetch("/api/data-backup",{cache:"no-store"});if(!response.ok)throw Error(((await response.json()) as {error?:string}).error||"백업 파일을 만들지 못했습니다.");const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");const disposition=response.headers.get("content-disposition")||"";link.href=url;link.download=disposition.match(/filename="([^"]+)"/)?.[1]||"juhwan-backup.json";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setResult("구조화 데이터를 백업했습니다.");toast.success("백업 파일을 내려받았습니다.")}catch(error){toast.error((error as Error).message)}finally{setBusy(null)}}
  async function restore(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(file.size>20*1024*1024){toast.error("백업 파일은 20MB 이하여야 합니다.");return}if(!window.confirm("운동 계획·홈 설정·투자 원장과 작성 콘텐츠를 이 백업으로 복원합니다. 운동 기록은 중복 없이 합쳐집니다. 계속할까요?"))return;setBusy("restore");setResult("");try{const text=await file.text();JSON.parse(text);const response=await fetch("/api/data-backup",{method:"POST",headers:{"content-type":"application/json"},body:text}),payload=await response.json() as {error?:string;counts?:{workoutSessions:number;contentPosts:number};excluded?:string[]};if(!response.ok)throw Error(payload.error||"복원하지 못했습니다.");setResult(`복원 완료 · 운동 ${payload.counts?.workoutSessions??0}건 · 콘텐츠 ${payload.counts?.contentPosts??0}건`);toast.success("백업 데이터를 복원했습니다.")}catch(error){toast.error(error instanceof SyntaxError?"JSON 백업 파일을 선택해 주세요.":(error as Error).message)}finally{setBusy(null)}}
  return <section className="backup-panel" aria-labelledby="backup-title"><div><p className="eyebrow">DATA RECOVERY</p><h3 id="backup-title">데이터 백업과 복원</h3><p>운동·루틴·홈 설정·투자 원장·작성 콘텐츠를 한 파일로 보관합니다. OAuth 비밀값과 업로드 사진 원본은 포함하지 않습니다.</p></div><div className="backup-actions"><Button type="button" variant="outline" disabled={Boolean(busy)} onClick={()=>void download()}>{busy==="export"?<RefreshCw className="animate-spin"/>:<Download/>}백업 내려받기</Button><label className="backup-upload" aria-disabled={Boolean(busy)}><Upload/>백업 복원<Input type="file" accept="application/json,.json" disabled={Boolean(busy)} onChange={e=>void restore(e)}/></label></div>{result&&<p className="backup-result" role="status">{result}</p>}<small>소스 코드와 공개 사진은 GitHub에서, 개인 기록은 이 백업 파일에서 복구합니다.</small></section>
}
