"use client";

import {ChangeEvent,Children,FormEvent,useEffect,useMemo,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {toast} from "sonner";
import {Plus,RefreshCw,Save,Trash2,X} from "lucide-react";
import {InvestmentGrowthChart} from "@/components/InvestmentGrowthChart";
import {buildInvestmentGrowth} from "@/lib/investment-growth";
import {validateInvestmentLedger} from "@/lib/investment-validation";
import type {InvestmentAccount,InvestmentCashflow,InvestmentDividend,InvestmentHolding,InvestmentLedger,InvestmentSnapshot,InvestmentCurrency} from "@/types/investment-ledger";

type Tab="overview"|"holdings"|"cashflows"|"dividends"|"snapshots"|"settings";
type EditState={kind:Exclude<Tab,"overview"|"settings">;id:string|null}|null;
const tabs:[Tab,string][]=[["overview","요약"],["holdings","자산"],["cashflows","입출금"],["dividends","배당"],["snapshots","월말 기록"],["settings","계좌·목표"]];
const krw=(v:number)=>new Intl.NumberFormat("ko-KR",{style:"currency",currency:"KRW",maximumFractionDigits:0}).format(v);
const usd=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v);
const pct=(v:number)=>`${v>=0?"+":""}${v.toFixed(1)}%`;
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
const num=(data:FormData,key:string)=>Number(data.get(key)??0);
const str=(data:FormData,key:string)=>String(data.get(key)??"").trim();
const byDate=<T extends {date:string}>(items:T[])=>[...items].sort((a,b)=>b.date.localeCompare(a.date));
const monthKey=(date:string)=>date.slice(0,7);

function valueKrw(amount:number,currency:InvestmentCurrency,exchangeRate:number|undefined,fallback:number){return currency==="KRW"?amount:amount*(exchangeRate||fallback);}
function metrics(ledger:InvestmentLedger){
  const snapshots=byDate(ledger.snapshots),latest=snapshots[0],fx=latest?.exchangeRate||1350;
  const holdingKrw=ledger.holdings.reduce((sum,h)=>sum+valueKrw(h.quantity*h.currentPrice,h.currency,undefined,fx),0);
  const totalKrw=latest?.totalKrw??holdingKrw,totalUsd=fx?totalKrw/fx:0;
  const ordered=[...ledger.snapshots].sort((a,b)=>a.date.localeCompare(b.date)),growth=buildInvestmentGrowth(ledger);
  const twr=(growth.at(-1)?.index??100)-100;
  const dividendKrw=ledger.dividends.reduce((sum,d)=>sum+valueKrw(d.amount,d.currency,d.exchangeRate,fx),0);
  const latestMonth=latest?monthKey(latest.date):monthKey(today());
  const monthly=new Map<string,number>();
  for(const d of ledger.dividends)monthly.set(monthKey(d.date),(monthly.get(monthKey(d.date))??0)+valueKrw(d.amount,d.currency,d.exchangeRate,fx));
  const recentMonths=[...monthly.entries()].filter(([m])=>m<=latestMonth).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,12);
  const avg12=recentMonths.reduce((sum,[,v])=>sum+v,0)/12;
  const allocation=new Map<string,number>();
  for(const h of ledger.holdings){const v=valueKrw(h.quantity*h.currentPrice,h.currency,undefined,fx);allocation.set(h.category,(allocation.get(h.category)??0)+v);}
  const allocations=[...allocation.entries()].map(([name,value])=>({name,value,weight:holdingKrw?value/holdingKrw*100:0})).sort((a,b)=>b.value-a.value);
  const first=ordered[0];
  const bench=(key:"kospi"|"sp500"|"nasdaq")=>first?.[key]&&latest?.[key]?(latest[key]!/first[key]!-1)*100:null;
  const age=31,years=Math.max(0,ledger.settings.retirementAge-age),projected=avg12*Math.pow(1+ledger.settings.expectedAnnualDividendGrowthPercent/100,years);
  return {latest,fx,totalKrw,totalUsd,twr,growth,dividendKrw,avg12,monthly,recentMonths,allocations,benchmarks:{kospi:bench("kospi"),sp500:bench("sp500"),nasdaq:bench("nasdaq")},projected};
}

export function InvestmentTracker(){
  const [ledger,setLedger]=useState<InvestmentLedger|null>(null),[revision,setRevision]=useState(0),[tab,setTab]=useState<Tab>("overview"),[editing,setEditing]=useState<EditState>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
  useEffect(()=>{void load()},[]);
  async function load(){setError("");try{const r=await fetch("/api/investment-ledger",{cache:"no-store"}),j=await r.json() as {ledger?:InvestmentLedger;revision?:number;error?:string};if(!r.ok||!j.ledger)throw Error(j.error??"투자 원장을 불러오지 못했습니다.");setLedger(j.ledger);setRevision(j.revision??0);}catch(e){setError((e as Error).message)}}
  async function persist(next:InvestmentLedger,message="저장했습니다."){setSaving(true);setError("");try{const r=await fetch("/api/investment-ledger",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({ledger:next,revision})}),j=await r.json() as {revision?:number;error?:string};if(!r.ok)throw Error(j.error??"저장하지 못했습니다.");setLedger(next);setRevision(j.revision??revision+1);setEditing(null);toast.success(message);}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  const m=useMemo(()=>ledger?metrics(ledger):null,[ledger]);
  if(!ledger||!m)return <section className="invest-tracker surface-panel"><div className="tracker-head"><div><p className="eyebrow">PRIVATE LEDGER</p><h2>내 투자 원장</h2></div><Button variant="ghost" onClick={()=>void load()}><RefreshCw/>다시 불러오기</Button></div><p className="tracker-empty">{error||"투자 원장을 불러오는 중입니다."}</p></section>;
  const accountName=(id:string)=>ledger.accounts.find(a=>a.id===id)?.name??"삭제된 계좌";
  const remove=(kind:Exclude<Tab,"overview"|"settings">,id:string)=>{if(!confirm("이 기록을 삭제할까요?"))return;const next={...ledger,[kind]:ledger[kind].filter(x=>x.id!==id)} as InvestmentLedger;void persist(next,"삭제했습니다.")};
  return <section className="invest-tracker" aria-label="내 투자 원장">
    <div className="tracker-head"><div><p className="eyebrow">PRIVATE LEDGER</p><h2>내 투자 원장</h2><p>금액과 보유 수량은 본인에게만 표시됩니다.</p></div><span className="private-chip">본인 전용</span></div>
    <nav className="tracker-tabs" aria-label="투자 원장 메뉴">{tabs.map(([key,label])=><button type="button" className={tab===key?"active":""} aria-current={tab===key?"page":undefined} key={key} onClick={()=>{setTab(key);setEditing(null)}}>{label}</button>)}</nav>
    {error&&<p className="tracker-error" role="alert">{error}</p>}
    {tab==="overview"&&<Overview ledger={ledger} m={m}/>}
    {tab==="holdings"&&<><SectionHeader title="보유 자산" count={ledger.holdings.length} onAdd={()=>setEditing({kind:"holdings",id:null})}/>{editing?.kind==="holdings"&&<HoldingForm ledger={ledger} item={ledger.holdings.find(x=>x.id===editing.id)} saving={saving} onCancel={()=>setEditing(null)} onSave={x=>void persist({...ledger,holdings:upsert(ledger.holdings,x)},"보유 자산을 저장했습니다.")}/>}<RecordTable empty="등록된 보유 자산이 없습니다.">{byName(ledger.holdings).map(h=><article className="tracker-row" key={h.id}><div><strong>{h.symbol}</strong><span>{h.name} · {accountName(h.accountId)} · {h.category}</span></div><div><b>{h.currency==="USD"?usd(h.quantity*h.currentPrice):krw(h.quantity*h.currentPrice)}</b><span>{h.quantity.toLocaleString()}주 · 평단 {h.averagePrice.toLocaleString()}</span></div><RowActions onEdit={()=>setEditing({kind:"holdings",id:h.id})} onDelete={()=>remove("holdings",h.id)}/></article>)}</RecordTable></>}
    {tab==="cashflows"&&<><SectionHeader title="입출금 내역" count={ledger.cashflows.length} onAdd={()=>setEditing({kind:"cashflows",id:null})}/>{editing?.kind==="cashflows"&&<CashflowForm ledger={ledger} item={ledger.cashflows.find(x=>x.id===editing.id)} saving={saving} onCancel={()=>setEditing(null)} onSave={x=>void persist({...ledger,cashflows:upsert(ledger.cashflows,x)},"입출금 내역을 저장했습니다.")}/>}<RecordTable empty="등록된 입출금 내역이 없습니다.">{byDate(ledger.cashflows).map(x=><article className="tracker-row" key={x.id}><div><strong>{x.type==="deposit"?"입금":"출금"} · {x.date}</strong><span>{accountName(x.accountId)}{x.note?` · ${x.note}`:""}</span></div><div><b className={x.type==="deposit"?"positive":"negative"}>{x.type==="deposit"?"+":"-"}{x.currency==="USD"?usd(x.amount):krw(x.amount)}</b><span>{x.currency==="USD"&&x.exchangeRate?`환율 ${x.exchangeRate.toLocaleString()}원`:""}</span></div><RowActions onEdit={()=>setEditing({kind:"cashflows",id:x.id})} onDelete={()=>remove("cashflows",x.id)}/></article>)}</RecordTable></>}
    {tab==="dividends"&&<><SectionHeader title="배당 내역" count={ledger.dividends.length} onAdd={()=>setEditing({kind:"dividends",id:null})}/>{editing?.kind==="dividends"&&<DividendForm ledger={ledger} item={ledger.dividends.find(x=>x.id===editing.id)} saving={saving} onCancel={()=>setEditing(null)} onSave={x=>void persist({...ledger,dividends:upsert(ledger.dividends,x)},"배당 내역을 저장했습니다.")}/>}<RecordTable empty="등록된 배당 내역이 없습니다.">{byDate(ledger.dividends).map(x=><article className="tracker-row" key={x.id}><div><strong>{x.symbol} · {x.date}</strong><span>{accountName(x.accountId)}{x.note?` · ${x.note}`:""}</span></div><div><b>{x.currency==="USD"?usd(x.amount):krw(x.amount)}</b><span>{krw(valueKrw(x.amount,x.currency,x.exchangeRate,m.fx))}</span></div><RowActions onEdit={()=>setEditing({kind:"dividends",id:x.id})} onDelete={()=>remove("dividends",x.id)}/></article>)}</RecordTable></>}
    {tab==="snapshots"&&<><SectionHeader title="월말 기록" count={ledger.snapshots.length} onAdd={()=>setEditing({kind:"snapshots",id:null})}/>{editing?.kind==="snapshots"&&<SnapshotForm item={ledger.snapshots.find(x=>x.id===editing.id)} saving={saving} onCancel={()=>setEditing(null)} onSave={x=>void persist({...ledger,snapshots:upsert(ledger.snapshots,x)},"월말 기록을 저장했습니다.")}/>}<RecordTable empty="월말 스냅샷을 추가하면 TWR과 지수 비교가 계산됩니다.">{byDate(ledger.snapshots).map(x=><article className="tracker-row snapshot-row" key={x.id}><div><strong>{x.date}</strong><span>환율 {x.exchangeRate.toLocaleString()}원</span>{x.note&&<p><b>내 소감</b>{x.note}</p>}{x.marketSummary&&<p><b>AI 월간 증시 요약</b>{x.marketSummary}</p>}</div><div><b>{usd(x.totalKrw/x.exchangeRate)}</b><span>{krw(x.totalKrw)}</span>{x.marketSources?.length?<small>공식 자료 {x.marketSources.length}개</small>:null}</div><RowActions onEdit={()=>setEditing({kind:"snapshots",id:x.id})} onDelete={()=>remove("snapshots",x.id)}/></article>)}</RecordTable></>}
    {tab==="settings"&&<Settings ledger={ledger} saving={saving} onSave={next=>void persist(next,"계좌와 목표를 저장했습니다.")}/>}
  </section>;
}

function Overview({ledger,m}:{ledger:InvestmentLedger;m:ReturnType<typeof metrics>}){
  const bills=ledger.settings.monthlyBillsKrw,coverage=bills?m.avg12/bills*100:0,target=ledger.settings.monthlyDividendTargetKrw,progress=target?m.avg12/target*100:0;
  const currentMonth=monthKey(m.latest?.date??today()),monthDividend=m.monthly.get(currentMonth)??0;
  const validation=validateInvestmentLedger(ledger),problems=validation.checks.filter(item=>item.level!=="ok").length;
  return <div className="tracker-overview">
    <section className="tracker-balance"><span>총 투자자산 · USD</span><strong>{usd(m.totalUsd)}</strong><small>{krw(m.totalKrw)} · 적용 환율 {m.fx.toLocaleString()}원</small></section>
    <dl className="tracker-metrics"><div><dt>누적 TWR</dt><dd className={m.twr>=0?"positive":"negative"}>{ledger.snapshots.length<2?"—":pct(m.twr)}</dd><small>입출금 영향 제외</small></div><div><dt>{currentMonth.slice(5)}월 배당</dt><dd>{krw(monthDividend)}</dd><small>12개월 평균 {krw(m.avg12)}</small></div><div><dt>누적 배당</dt><dd>{krw(m.dividendKrw)}</dd><small>{ledger.dividends.length}건</small></div><div><dt>월 목표 달성</dt><dd>{target?`${Math.min(progress,999).toFixed(0)}%`:"—"}</dd><small>목표 {krw(target)}</small></div></dl>
    <section className="tracker-card validation-card"><div className="tracker-card-head"><div><span>원장 무결성</span><h3>데이터 검증</h3></div><b data-level={problems?"warning":"ok"}>{problems?`${problems}건 확인`:"정상"}</b></div>{m.latest&&<dl className="validation-summary"><div><dt>스냅샷</dt><dd>{krw(validation.recordedKrw)}</dd></div><div><dt>보유액 · {validation.basis}</dt><dd>{krw(validation.matchedKrw)}</dd></div><div><dt>차이</dt><dd className={Math.abs(validation.differenceKrw)>Math.max(1000,validation.recordedKrw*.001)?"negative":"positive"}>{krw(validation.differenceKrw)}</dd></div><div><dt>별도 현금</dt><dd>{krw(validation.cashKrw)}</dd></div></dl>}<ul className="validation-list">{validation.checks.map((item,index)=><li key={`${item.title}-${index}`} data-level={item.level}><strong>{item.title}</strong><span>{item.detail}</span></li>)}</ul></section>
    <section className="tracker-card growth-card"><div className="tracker-card-head"><div><span>월간 성장 곡선</span><h3>달러 평가액 추이</h3></div><b>{m.growth.length}회 기록</b></div><InvestmentGrowthChart mode="usd" points={m.growth.map(point=>({date:point.date,value:point.usd}))}/><p className="growth-chart-note">월말 원화 평가액을 당시 입력한 환율로 환산했습니다. 추가 입금과 출금도 평가액 변화에 포함됩니다.</p></section>
    <div className="tracker-grid"><section className="tracker-card"><div className="tracker-card-head"><div><span>자산 배분</span><h3>분류별 현재가 비중</h3></div><b>{ledger.holdings.length}개</b></div>{m.allocations.length?<div className="treemap">{m.allocations.map((x,i)=><div key={x.name} style={{flexGrow:Math.max(x.weight,8)}} data-tone={i%4}><strong>{x.name}</strong><span>{x.weight.toFixed(1)}%</span></div>)}</div>:<Empty text="보유 자산을 등록하면 비중이 표시됩니다."/>}</section>
      <section className="tracker-card"><div className="tracker-card-head"><div><span>벤치마크</span><h3>첫 기록=100 수익률</h3></div><b>{ledger.snapshots.length}회</b></div><div className="benchmark-list"><Benchmark label="내 계좌 TWR" value={ledger.snapshots.length<2?null:m.twr}/><Benchmark label="KOSPI" value={m.benchmarks.kospi}/><Benchmark label="S&P 500" value={m.benchmarks.sp500}/><Benchmark label="NASDAQ" value={m.benchmarks.nasdaq}/></div></section>
      <section className="tracker-card"><div className="tracker-card-head"><div><span>배당 현금흐름</span><h3>최근 12개월</h3></div><b>{krw(m.avg12)}/월</b></div>{m.recentMonths.length?<div className="dividend-bars">{[...m.recentMonths].reverse().map(([month,value])=>{const max=Math.max(...m.recentMonths.map(([,v])=>v),1);return <div key={month}><span style={{height:`${Math.max(4,value/max*100)}%`}}/><small>{month.slice(5)}</small></div>})}</div>:<Empty text="배당 내역을 추가하면 월별 추이가 표시됩니다."/>}</section>
      <section className="tracker-card"><div className="tracker-card-head"><div><span>배당 목표</span><h3>현금흐름 해방도</h3></div><b>{bills?`${Math.min(coverage,999).toFixed(0)}%`:"생활비 미설정"}</b></div><div className="goal-progress"><span style={{width:`${Math.min(progress,100)}%`}}/><i>{progress.toFixed(0)}%</i></div><dl className="goal-list"><div><dt>현재 월평균</dt><dd>{krw(m.avg12)}</dd></div><div><dt>{ledger.settings.retirementAge}세 예상 월배당</dt><dd>{krw(m.projected)}</dd></div><div><dt>예상 성장률</dt><dd>연 {ledger.settings.expectedAnnualDividendGrowthPercent.toFixed(1)}%</dd></div></dl></section></div>
    <p className="tracker-note">TWR은 월말 평가액에서 해당 기간 순입금을 제거한 뒤 기간별 수익률을 연결합니다. 배당과 지수는 직접 입력한 환율·종가 기준이며 실시간 시세가 아닙니다.</p>
  </div>;
}

function SectionHeader({title,count,onAdd}:{title:string;count:number;onAdd:()=>void}){return <div className="tracker-section-head"><div><h3>{title}</h3><span>{count}건</span></div><Button type="button" onClick={onAdd}><Plus/>추가</Button></div>}
function RecordTable({children,empty}:{children:React.ReactNode;empty:string}){return <div className="tracker-records">{Children.count(children)?children:<Empty text={empty}/>}</div>}
function Empty({text}:{text:string}){return <p className="tracker-empty">{text}</p>}
function RowActions({onEdit,onDelete}:{onEdit:()=>void;onDelete:()=>void}){return <div className="tracker-row-actions"><Button type="button" variant="ghost" onClick={onEdit}>수정</Button><Button type="button" variant="ghost" aria-label="삭제" onClick={onDelete}><Trash2/></Button></div>}
function Benchmark({label,value}:{label:string;value:number|null}){return <div><span>{label}</span><strong className={value!==null&&value>=0?"positive":"negative"}>{value===null?"—":`${(100+value).toFixed(1)} (${pct(value)})`}</strong></div>}
function byName<T extends {symbol:string}>(items:T[]){return [...items].sort((a,b)=>a.symbol.localeCompare(b.symbol))}
function upsert<T extends {id:string}>(items:T[],item:T){const found=items.some(x=>x.id===item.id);return found?items.map(x=>x.id===item.id?item:x):[...items,item]}

function FormShell({title,saving,onCancel,children}:{title:string;saving:boolean;onCancel:()=>void;children:React.ReactNode}){return <section className="tracker-form"><div className="tracker-card-head"><h3>{title}</h3><Button type="button" variant="ghost" aria-label="닫기" onClick={onCancel}><X/></Button></div>{children}<div className="tracker-form-actions"><Button type="button" variant="ghost" onClick={onCancel}>취소</Button><Button type="submit" disabled={saving}><Save/>{saving?"저장 중":"저장"}</Button></div></section>}
function AccountSelect({accounts,value}:{accounts:InvestmentAccount[];value?:string}){return <label>계좌<select name="accountId" defaultValue={value??accounts[0]?.id} required>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label>}
function CurrencySelect({value="USD"}:{value?:InvestmentCurrency}){return <label>통화<select name="currency" defaultValue={value}><option value="USD">달러 (USD)</option><option value="KRW">원화 (KRW)</option></select></label>}

function HoldingForm({ledger,item,saving,onCancel,onSave}:{ledger:InvestmentLedger;item?:InvestmentHolding;saving:boolean;onCancel:()=>void;onSave:(x:InvestmentHolding)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);onSave({id:item?.id??uid("holding"),accountId:str(d,"accountId"),symbol:str(d,"symbol").toUpperCase(),name:str(d,"name"),category:str(d,"category"),currency:str(d,"currency") as InvestmentCurrency,quantity:num(d,"quantity"),averagePrice:num(d,"averagePrice"),currentPrice:num(d,"currentPrice")})}return <form onSubmit={submit}><FormShell title={item?"보유 자산 수정":"보유 자산 추가"} saving={saving} onCancel={onCancel}><div className="tracker-form-grid"><AccountSelect accounts={ledger.accounts} value={item?.accountId}/><label>종목 코드<Input name="symbol" required defaultValue={item?.symbol}/></label><label>종목명<Input name="name" required defaultValue={item?.name}/></label><label>자산 분류<Input name="category" required defaultValue={item?.category??"성장"} placeholder="성장, 인컴, 현금"/></label><CurrencySelect value={item?.currency}/><label>수량<Input name="quantity" type="number" min="0" step="any" required defaultValue={item?.quantity}/></label><label>평균 단가<Input name="averagePrice" type="number" min="0" step="any" required defaultValue={item?.averagePrice}/></label><label>현재가<Input name="currentPrice" type="number" min="0" step="any" required defaultValue={item?.currentPrice}/></label></div></FormShell></form>}
function CashflowForm({ledger,item,saving,onCancel,onSave}:{ledger:InvestmentLedger;item?:InvestmentCashflow;saving:boolean;onCancel:()=>void;onSave:(x:InvestmentCashflow)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),exchangeRate=num(d,"exchangeRate");onSave({id:item?.id??uid("flow"),date:str(d,"date"),accountId:str(d,"accountId"),type:str(d,"type") as InvestmentCashflow["type"],amount:num(d,"amount"),currency:str(d,"currency") as InvestmentCurrency,exchangeRate:exchangeRate||undefined,note:str(d,"note")})}return <form onSubmit={submit}><FormShell title={item?"입출금 수정":"입출금 추가"} saving={saving} onCancel={onCancel}><div className="tracker-form-grid"><label>일자<Input name="date" type="date" required defaultValue={item?.date??today()}/></label><AccountSelect accounts={ledger.accounts} value={item?.accountId}/><label>구분<select name="type" defaultValue={item?.type??"deposit"}><option value="deposit">입금</option><option value="withdrawal">출금</option></select></label><CurrencySelect value={item?.currency}/><label>금액<Input name="amount" type="number" min="0" step="any" required defaultValue={item?.amount}/></label><label>적용 환율 · USD만<Input name="exchangeRate" type="number" min="1" step="any" defaultValue={item?.exchangeRate}/></label><label className="wide">메모<Input name="note" defaultValue={item?.note}/></label></div></FormShell></form>}
function DividendForm({ledger,item,saving,onCancel,onSave}:{ledger:InvestmentLedger;item?:InvestmentDividend;saving:boolean;onCancel:()=>void;onSave:(x:InvestmentDividend)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),exchangeRate=num(d,"exchangeRate");onSave({id:item?.id??uid("dividend"),date:str(d,"date"),accountId:str(d,"accountId"),symbol:str(d,"symbol").toUpperCase(),amount:num(d,"amount"),currency:str(d,"currency") as InvestmentCurrency,exchangeRate:exchangeRate||undefined,note:str(d,"note")})}return <form onSubmit={submit}><FormShell title={item?"배당 수정":"배당 추가"} saving={saving} onCancel={onCancel}><div className="tracker-form-grid"><label>지급일<Input name="date" type="date" required defaultValue={item?.date??today()}/></label><AccountSelect accounts={ledger.accounts} value={item?.accountId}/><label>종목 코드<Input name="symbol" required defaultValue={item?.symbol}/></label><CurrencySelect value={item?.currency}/><label>세후 배당금<Input name="amount" type="number" min="0" step="any" required defaultValue={item?.amount}/></label><label>적용 환율 · USD만<Input name="exchangeRate" type="number" min="1" step="any" defaultValue={item?.exchangeRate}/></label><label className="wide">메모<Input name="note" defaultValue={item?.note}/></label></div></FormShell></form>}
function SnapshotForm({item,saving,onCancel,onSave}:{item?:InvestmentSnapshot;saving:boolean;onCancel:()=>void;onSave:(x:InvestmentSnapshot)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),optional=(key:string)=>{const v=num(d,key);return v||undefined};onSave({id:item?.id??uid("snapshot"),date:str(d,"date"),totalKrw:num(d,"totalKrw"),exchangeRate:num(d,"exchangeRate"),kospi:optional("kospi"),sp500:optional("sp500"),nasdaq:optional("nasdaq"),note:str(d,"note"),marketSummary:str(d,"marketSummary")||undefined,marketSources:item?.marketSources})}return <form onSubmit={submit}><FormShell title={item?"월말 기록 수정":"월말 기록 추가"} saving={saving} onCancel={onCancel}><div className="tracker-form-grid"><label>기준일<Input name="date" type="date" required defaultValue={item?.date??today()}/></label><label>총 평가액 (원)<Input name="totalKrw" type="number" min="0" step="1" required defaultValue={item?.totalKrw}/></label><label>원·달러 환율<Input name="exchangeRate" type="number" min="1" step="any" required defaultValue={item?.exchangeRate??1350}/></label><label>KOSPI 종가<Input name="kospi" type="number" min="1" step="any" defaultValue={item?.kospi}/></label><label>S&amp;P 500 종가<Input name="sp500" type="number" min="1" step="any" defaultValue={item?.sp500}/></label><label>NASDAQ 종가<Input name="nasdaq" type="number" min="1" step="any" defaultValue={item?.nasdaq}/></label><label className="wide">내 월말 소감<Textarea name="note" rows={4} maxLength={1200} defaultValue={item?.note} placeholder="그달의 판단, 감정, 다음 달에 지킬 원칙을 기록하세요."/></label><label className="wide">AI 월간 증시 뉴스 요약<Textarea name="marketSummary" rows={5} maxLength={2400} defaultValue={item?.marketSummary} placeholder="그달의 금리·물가·고용·시장 변동을 정리한 AI 초안을 검토해 저장하세요."/></label></div></FormShell></form>}

function Settings({ledger,saving,onSave}:{ledger:InvestmentLedger;saving:boolean;onSave:(x:InvestmentLedger)=>void}){
  const [draft,setDraft]=useState(ledger);
  const addAccount=()=>setDraft(x=>({...x,accounts:[...x.accounts,{id:uid("account"),name:"새 계좌",type:"일반",broker:""}]}));
  const removeAccount=(id:string)=>{if(draft.holdings.some(x=>x.accountId===id)||draft.cashflows.some(x=>x.accountId===id)||draft.dividends.some(x=>x.accountId===id)){toast.error("연결된 자산·입출금·배당을 먼저 정리해 주세요.");return}if(draft.accounts.length===1){toast.error("계좌는 하나 이상 필요합니다.");return}setDraft(x=>({...x,accounts:x.accounts.filter(a=>a.id!==id)}))};
  async function importLedger(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const next=JSON.parse(await file.text()) as InvestmentLedger;setDraft(next);onSave(next);}catch{toast.error("JSON 파일을 읽지 못했습니다.");}finally{e.target.value="";}}
  return <div className="tracker-settings"><section className="tracker-import"><div><p className="eyebrow">SPREADSHEET IMPORT</p><h3>투자기록시트 가져오기</h3><p>변환한 JSON으로 현재 원장을 교체합니다. 원본 금액은 본인 전용으로 저장됩니다.</p></div><label className="import-button">JSON 선택<Input aria-label="투자기록시트 JSON 선택" type="file" accept="application/json,.json" disabled={saving} onChange={e=>void importLedger(e)}/></label></section><div className="tracker-section-head"><div><h3>계좌</h3><span>원장의 분류 기준</span></div><Button type="button" variant="secondary" onClick={addAccount}><Plus/>계좌 추가</Button></div><div className="account-list">{draft.accounts.map((a,i)=><article key={a.id}><Input aria-label="계좌명" value={a.name} onChange={e=>setDraft(x=>({...x,accounts:x.accounts.map((v,j)=>j===i?{...v,name:e.target.value}:v)}))}/><Input aria-label="증권사" placeholder="증권사" value={a.broker} onChange={e=>setDraft(x=>({...x,accounts:x.accounts.map((v,j)=>j===i?{...v,broker:e.target.value}:v)}))}/><select aria-label="계좌 유형" value={a.type} onChange={e=>setDraft(x=>({...x,accounts:x.accounts.map((v,j)=>j===i?{...v,type:e.target.value as InvestmentAccount["type"]}:v)}))}>{["일반","ISA","연금저축","IRP","퇴직연금","기타"].map(x=><option key={x}>{x}</option>)}</select><Button type="button" variant="ghost" aria-label="계좌 삭제" onClick={()=>removeAccount(a.id)}><Trash2/></Button></article>)}</div><div className="tracker-section-head"><div><h3>배당 목표</h3><span>생활비 충당과 은퇴 시뮬레이션</span></div></div><div className="tracker-form tracker-form-grid"><label>월 고정생활비 (원)<Input type="number" min="0" value={draft.settings.monthlyBillsKrw} onChange={e=>setDraft(x=>({...x,settings:{...x.settings,monthlyBillsKrw:Number(e.target.value)}}))}/></label><label>목표 월배당 (원)<Input type="number" min="0" value={draft.settings.monthlyDividendTargetKrw} onChange={e=>setDraft(x=>({...x,settings:{...x.settings,monthlyDividendTargetKrw:Number(e.target.value)}}))}/></label><label>은퇴 기준 나이<Input type="number" min="31" max="100" value={draft.settings.retirementAge} onChange={e=>setDraft(x=>({...x,settings:{...x.settings,retirementAge:Number(e.target.value)}}))}/></label><label>연 배당 성장률 (%)<Input type="number" min="-100" max="100" step="0.1" value={draft.settings.expectedAnnualDividendGrowthPercent} onChange={e=>setDraft(x=>({...x,settings:{...x.settings,expectedAnnualDividendGrowthPercent:Number(e.target.value)}}))}/></label></div><div className="tracker-save-row"><Button type="button" disabled={saving} onClick={()=>onSave(draft)}><Save/>{saving?"저장 중":"계좌와 목표 저장"}</Button></div></div>
}
